# Define coordinates
Doosprepickup = p[0.53372, -0.27139, 0.32368, 0.0, 3.141, 0]
Doospickup = p[0.53372, -0.27139, 0.22368, 0.000, 3.141, 0]
doospickupz = 0.22368
Doospostpickup = p[0.53372, -0.27139, 0.37368, 0.0, 3.141, 0]
Doospostpickupz = 0.37368
Doosmidpostpickup = p[0.53372, -0.27139, 0.33368, 0.0, 3.141, 0]
Doosmidpostpickupz = 0.33368

#giftbox plaatsen in mold coords
DoosBovenMoldHoog = p[0.25603, -0.69603, 0.3592, 0.039, 2.287, 2.151]
DoosBovenMoldMidden = p[0.25603, -0.69603, 0.09392, 0.039, 2.287, 2.151]
DoosBovenMoldMiddenz = 0.09392
DoosBovenMold = p[0.25603, -0.69603, 0.06292, 0.039, 2.287, 2.151]
DoosBovenMoldz = 0.06292
NaDoosPlaatsing = p[0.25603, -0.7495, 0.06292, 0.039, 2.287, 2.151]

PreDoosPickupMold = p[0.25603, -0.7495, 0.04850, 0.039, 2.287, 2.151]
PreDoosPickupMoldz = 0.04850
DoosPickupMold = p[0.25103, -0.69603, 0.04850, 0.039, 2.287, 2.151]

PreDoosPickupMoldNaWallet = p[0.25103, -0.7495, 0.14087, 0.039, 2.287, 2.151]


NaDoosPlaatsingHoog = p[0.25103, -0.69603, 0.3592, 0.039, 2.287, 2.151]
#wallet oppakken van tafel coords
pickup = p[0.55587, 0.12303, 0.19429, 0.029, -3.141, 0]
postpickup = p[0.55587, 0.12303, 0.39429, 0.029, -3.141, 0]
postpickupz = 0.39429
#scan positie van wallet datamatrix
posscan = p[0.29504, -0.32626, 0.27504, 0.080, 3.141, 0]

#wallet oppakken van tafel coords
Walletprepickup = p[0.55587, 0.12303, 0.39429, 0.029, -3.141, 0]
Walletpickup = p[0.55587, 0.12303, 0.19429, 0.029, -3.141, 0]
Walletpickupz = 0.19429
Walletpostpickup = p[0.55587, 0.12303, 0.39429, 0.029, -3.141, 0]
Walletpostpickupz = 0.39429
#posscanPost = p[0.29504, -0.32626, 0.47504, 0.080, 3.141, 0]

#wallet plaatsen in giftbox coords
WalletPrePlacingHigh = p[0.307, -0.69686, 0.30270, 0.170, -2.297, -2.234]
WalletPrePlacingMedium = p[0.28297, -0.68467,0.10530, 0.916, -2.510, -2.331]
WalletPrePlacingLow = p[0.27235, -0.68424, 0.09079, 1.029, -2.516, -2.383]
WalletPlacing = p[0.25893, -0.68811, 0.08162, 1.013, -2.486, -2.411]
WalletPostPlacing = p[0.27990, -0.68949, 0.08919, 1.165, -2.601, -2.417]
WalletPostPlacingBack = p[0.25395, -0.72747, 0.09172, 0.073, -2.506, -2.081]
WalletPushingAfterPlacing = p[0.25533, -0.68291, 0.11747, 0.011, 2.583, 1.719]
WalletAfter = p[0.25900, -0.72501, 0.14087, 0.003, 2.641, 1.612]

ip = "192.168.0.43"
socket_name = "socket1"

global failcount = 0



# Function to apply new Z
def set_pose_z(pose, new_z):
    return p[pose[0], pose[1], new_z, pose[3], pose[4], pose[5]]
end

# function to make coords into pose 
def makepose(coords):
    return p[coords[2], coords[3], coords[4], coords[5], coords[6], coords[7]]
end

def get_sig(coords):
    return coords[1]
end

def get_fail(coords):
    return coords[8]
end

sec activate_suction_cup():
    set_standard_digital_out(0, True)
end

sec deactivate_suction_cup():
    set_standard_digital_out(0, False)
end

sec open_gripper():
    set_standard_analog_out(0,0)
end

sec close_gripper_pre_wallet():
    set_standard_analog_out(0,0.282)
end

sec close_gripper_box():
    set_standard_analog_out(0,0.17)
end

sec close_gripper_full():
    set_standard_analog_out(0,0.33)
end
# Function to move to target
def moveto_target_coords(coords):

    pose = makepose(coords)
    sig = get_sig(coords)
    set_standard_analog_out(0, 0)
    if sig == 1:
      set_standard_analog_out(0, 0.282)
    end

    
    if sig == 0:
       set_standard_analog_out(0, 0.0)
        movel(predoospickup, t = 0.1)
        set_standard_digital_out(0, True)
        movel(pose, t = 0.5)
   
        movel(predoospickup, t = 0.1)
        set_standard_analog_out(0, 0.33)
        sleep(0.7)
        set_standard_digital_out(0, False)
        #movel(postdoospickup)
    end
      
    if sig == 1:
        movej(prewalletpickup, t= 0.1)
        set_standard_analog_out(0, 0.275)
        sleep(2.5)
        set_standard_digital_out(1, True)
        sleep(0.5)
        set_standard_digital_out(2, True)
        set_standard_analog_out(1, 0.0)
   
   
   
   
        sleep(0.1)
        movel(pose, t = 0.1)
        set_standard_analog_out(0, 0.33)
        sleep(2)
        movel(prewalletpickup, t = 0.1)
    end
end


def moveto_scanner():
  movej(posscan, a=1.2, v=0.25)
end


def scan(coords):
  sig, fail = get_sigs(coords)
  if sig == 0:
    if fail == 1:
      moveto_opener(failstate=False, sig)
    else:
      moveto_opener(failstate=True, sig)
    end
  else:
    socket_send_string(socket_name, "SCAN_WALLET")
    while True:
      correct = socket_read_string(socket_name, timeout=0)
      if correct == "true":
        moveto_opener(failstate=False, sig)
        break
      elif correct == "false":
        moveto_opener(failstate=True, sig)
        break
      else:
        popup("Error: Unknown scan result", title="Error", error=True)
        textmsg("error: unknown scan result")
        socket_send_string("ERROR", socket_name)
        sleep(1)
        continue
      end
    end
  end
end

     
  
     

    
    

def moveto_home():
    movel(home_pos, a=1.2, v=0.25)
end

def moveto_opener(failstate=False, sig):
   if sig == 1:
       if fail == 1:
           movej(postposscan)
           movel(walletplacing1)
           set_standard_analog_out(0, 0.0)
           sleep(0.2)
           movel(postwalletplacing)
           set_standard_analog_out(1, 0.23) 
           sleep(1)
           set_standard_digital_out(2, False)
           sleep(0.1)
           set_standard_digital_out(1, False)
           set_standard_analog_out(1, 0.0) 
           set_standard_analog_out(0, 0.25)
       else:
           movej(failpos)
           set_standard_analog_out(0, 0.0)
       end
    else:
    
        if failstate:
              set_standard_analog_out(0, 0.33)
              movej(fail, a=1.2, v=0.5)
              movej(set_pose_z(failurepos, lowerzwallet))
              set_standard_analog_out(0, 0.2)
              movej(set_pose_z(failurepos, raisezwallet))
        else:
        
            movej(DoosBovenMoldHoog)
            sleep(0.01)
            movel(set_pose_z(DoosBovenMoldHoog, DoosBovenMoldMiddenz))
            sleep(0.01)
            movel(set_pose_z(DoosBovenMoldMidden, DoosBovenMoldz))
            sleep(0.02)
            set_standard_analog_out(0, 0.27)
            sleep(1.2)
            movel(NaDoosPlaatsing)
            sleep(0.1)
            movel(NaDoosPlaatsingHoog)
            set_standard_analog_out(1, 0.11)
      end
    end
end
        


def pickupfinishedbox():
   set_standard_digital_out(2, False)
   sleep(0.1)
   set_standard_digital_out(1, False)
   set_standard_analog_out(1, 0.0) 
   set_standard_analog_out(0, 0.25)
   sleep(2)
   movel(pickbox, t = 0.1)
   
   set_standard_analog_out(0, 0.33)
   sleep(1)
   movel(afterpickbox, t = 0.1)
   movel(postafterpickbox, t = 0.5)
   movel(finalpospre1, t = 0.1)
   movel(finalpospre2, t = 0.1)
   set_standard_analog_out(0, 0.0)
   sleep(1)
   movel(finalposreal, t = 0.1)
   movel(finalpospre1, t = 0.1)
   movej(predoospickup, t = 0.1)

end 


def check_error_count():
    global failcount
    failcount = failcount + 1
    return failcount >= 4
end 


def main():
  
    socket_open(ip, 12344, socket_name)
    
    
    while True:
        if socket_read_string(socket_name, timeout=0) != "start":
          sleep(0.1)
          continue
        end
        socket_send_string("SEND_GIFTBOX_COORDS", socket_name)
        
        coords = socket_read_ascii_float(8, socket_name, timeout=0)
        textmsg("Received coordinates: " + str(coords))
        if coords[0] != 8:
          popup("Error: Invalid coordinates received", title="Error", error=True)
          textmsg("Error: Invalid coordinates received")
          
    #       socket_send_string('ERROR', socket_name)
    #       sleep(1)
    #       continue
    #     end
    #     sig, fail = get_sigs(coords)
    #     positiion = makepose(coords)
    #     moveto_target_coords(coords)
        
    #     if sig == 0:
    #       if fail == 1:
    #         moveto_opener(failstate=False, sig)
    #       else:
    #         moveto_opener(failstate=True, sig)
    #       end
          

    #     else:
    #       moveto_scanner()
    #       socket_send_string(socket_name, 'SCAN_WALLET')
    #       while True:
    #         correct = socket_read_string(socket_name, timeout=0)
    #         if correct == 'true':
    #           moveto_opener(failstate=False, sig)
    #           break
    #         elif correct == 'false':
    #           moveto_opener(failstate=True, sig)
    #           break
    #         else:
    #           popup('Error: Unknown scan result', title='Error', error=True)
    #           textmsg('error: unknown scan result')
    #         end
    #       end
    #     end

    #     if fail:
    #       too_many_errors = check_error_count()
    #       if too_many_errors:
    #         popup('Error: Too many failed attempts', title='Error', error=True)
    #         textmsg('Error: Too many failed attempts')
    #         socket_send_string('ERROR', socket_name)
    #         break
    #       else:
    #         continue
    #       end
    #     end
        

    #     pickupfinishedbox()
    #   end
    # moveto_home() 
    # socket_close(socket_name)
    end 
  



# --- CALL THE FUNCTION SAFELY ---
main()
