##giftbox opppakken van doos coords 
Doosprepickup = p[0.53372, -0.27139, 0.32368, 0.0, 3.141, 0]
Doospickup = p[0.53372, -0.27139, 0.22368, 0.000, 3.141, 0]
Doospostpickup = p[0.53372, -0.27139, 0.37368, 0.0, 3.141, 0]
Doosmidpostpickup = p[0.53372, -0.27139, 0.33368, 0.0, 3.141, 0]

#giftbox plaatsen in mold coords
DoosBovenMoldHoog = p[0.25603, -0.69603, 0.3592, 0.039, 2.287, 2.151]
DoosBovenMoldMidden = p[0.25603, -0.69603, 0.09392, 0.039, 2.287, 2.151]
DoosBovenMold = p[0.25603, -0.69603, 0.06292, 0.039, 2.287, 2.151]
NaDoosPlaatsing = p[0.25603, -0.7495, 0.06292, 0.039, 2.287, 2.151]
PreDoosPickupMold = p[0.25603, -0.7495, 0.04850, 0.039, 2.287, 2.151]
DoosPickupMold = p[0.25103, -0.69603, 0.04850, 0.039, 2.287, 2.151]

PreDoosPickupMoldNaWallet = p[0.25103, -0.7495, 0.14087, 0.039, 2.287, 2.151]


NaDoosPlaatsingHoog = p[0.25103, -0.69603, 0.3592, 0.039, 2.287, 2.151]
#wallet oppakken van tafel coords
pickup = p[0.55587, 0.12303, 0.19429, 0.029, -3.141, 0]
postpickup = p[0.55587, 0.12303, 0.39429, 0.029, -3.141, 0]
#scan positie van wallet datamatrix
posscan = p[0.29504, -0.32626, 0.27504, 0.080, 3.141, 0]

#wallet oppakken van tafel coords
Walletprepickup = p[0.55587, 0.12303, 0.39429, 0.029, -3.141, 0]
Walletpickup = p[0.55587, 0.12303, 0.19429, 0.029, -3.141, 0]
Walletpostpickup = p[0.55587, 0.12303, 0.39429, 0.029, -3.141, 0]
#posscanPost = p[0.29504, -0.32626, 0.47504, 0.080, 3.141, 0]

#wallet plaatsen in giftbox coords
WalletPrePlacingHigh = p[0.307, -0.69686, 0.30270, 0.170, -2.297, -2.234]
WalletPrePlacingMedium = p[0.28297, -0.68467,0.10530, 0.916, -2.510, -2.331]
WalletPrePlacingLow = p[0.27235, -0.68424, 0.09079, 1.029, -2.516, -2.383]
WalletPlacing = p[0.25893, -0.68811, 0.08162, 1.013, -2.486, -2.411]
WalletPostPlacing = p[0.27990, -0.68949, 0.08919, 1.165, -2.601, -2.417]
WalletPostPlacingBack = p[0.25395, -0.72747, 0.09172, 0.073, -2.506, -2.081]
WalletPushingAfterPlacing = p[0.25533, -0.68291, 0.11747, 0.011, 2.583, 1.719]
WalletAfter = p[0.25900, -0.72501, 0.14087, 0.003, 2.641, 1.612]

def main():
   set_standard_analog_out(0, 0.0)
   movel(Doosprepickup, t=0.2)
   movel(Doospickup, t= 0.1)
   set_standard_digital_out(0, True)
   set_standard_analog_out(0, 0.167)
   movel(Doosmidpostpickup)
   set_standard_analog_out(0, 0.33)
   sleep(0.4)
   set_standard_digital_out(0, False)
   movel(Doospostpickup, t=0.1)

   movej(DoosBovenMoldHoog, t= 0.2)
   sleep(0.01)
   movel(DoosBovenMoldMidden, t=0.1)
   sleep(0.01)
   movel(DoosBovenMold, t=0.1)
   sleep(0.02)
   set_standard_analog_out(0, 0.27)
   sleep(1.2)
   movel(NaDoosPlaatsing)
   sleep(0.1)
   movel(NaDoosPlaatsingHoog, t=0.1)
   set_standard_analog_out(1, 0.11)
   set_standard_analog_out(0, 0.29)
   sleep(0.1)
   movej(Walletprepickup, t=0.4)
   sleep(0.01)
   movel(Walletpickup, t=0.1)
   set_standard_analog_out(0, 0.33)
   set_standard_digital_out(1, True)
   sleep(0.5)
   set_standard_digital_out(2, True)
   movel(Walletpostpickup, t=0.1)
   set_standard_analog_out(1, 0.055)
   sleep(0.01)
   movej(posscan, t=0.3)
   sleep(0.01)
   movel(WalletPrePlacingHigh, t=0.1)
   sleep(0.01)
   movel(WalletPrePlacingMedium, t=0.1)
   sleep(0.01)
   movel(WalletPrePlacingLow, t=0.1)
   sleep(0.01)
   movel(WalletPlacing)
   sleep(0.01)
   set_standard_analog_out(0, 0.289)
   sleep(0.5)
   movel(WalletPostPlacing, t=0.1)
   sleep(0.01)
   movel(WalletPostPlacingBack, t =0.1)
   sleep(0.01)
   movel(WalletPushingAfterPlacing, t= 0.1)
   sleep(0.01)
   movel(WalletAfter, t= 0.1)
   sleep(0.02)
   set_standard_analog_out(1, 0.11)
   movel(PreDoosPickupMoldNaWallet, t= 0.1)
   set_standard_analog_out(0, 0.25)
   movel(PreDoosPickupMold, t= 0.1)
   sleep(1)
   set_standard_digital_out(2, False)
   set_standard_digital_out(1, False)
   sleep(0.5)
   set_standard_analog_out(1, 0.055)
   sleep(1)
   movel(DoosPickupMold, t=0.1)
   sleep(0.1)
   set_standard_analog_out(0, 0.33)
   sleep(0.5)
   movel(DoosBovenMoldHoog, t=0.1)
   sleep(0.01)
   movel(Doospostpickup, t=0.2)
   movel(Doosmidpostpickup, t=0.1)
   set_standard_analog_out(0, 0.0)
   
   sleep(3000) 

end


main()
