########################################
# ----------- POSITIONS ----------------
########################################

failpos = p[0.87482, 0.02985, 0.33166, 2.469, -2.390, -2.263]
doospickup = p[0.58202, 0.09542, 0.30634, 0.014, 2.214, 2.210]
predoospickup = p[0.58202, 0.0, 0.30634, 0.014, 2.214, 2.210]
postdoospickup = p[0.58202, -0.06022, 0.30634, 0.014, 2.214, 2.210]
#midpostdoospickup = p[0.58422, 0.15191, 0.25089, 0.013, 2.502, 1.904]

##+ 80.6 mm x as voor tweede doos
xstart = 0.58922
xnieuw1 = xstart + 0.072
xnieuw = xstart + 0.073 * 2
xoffsetbox = -0.03216
doospickupxnieuw = 0.87482 + (xoffsetbox * 2 - 0.002)
doosplacexnieuw = 0.87482 + xoffsetbox * 2
doospickup = p[0.87482, 0.13985, 0.33166, 2.469, -2.390, -2.263]
predoospickup = p[0.87482, 0.02985, 0.33166, 2.469, -2.390, -2.263]
postdoospickup = p[0.87482, -0.06022, 0.33166, 2.469, -2.390, -2.263]

xoffsetwallet = 0.10431
walletpickupy = -0.17429
walletpickupx = 0.55287
walletpickupynieuw = walletpickupy - (0.035 * 2 - 0.001)
walletpickupxnieuw = walletpickupx + xoffsetwallet *2
prewalletpickup = p[0.55287,  walletpickupynieuw, 0.350, 0.000, 3.141, -0.000]
walletpickup = p[0.55287, walletpickupynieuw, 0.20024, 0.000, 3.141, -0.000]
posscan = p[0.76201, -0.02612, 0.32801, 0.021, 3.131, -0.177]
postposscan = p[0.79712, -0.02612, 0.50080, 0.021, 3.131, -0.177]

prewalletpickup = p[walletpickupxnieuw,  walletpickupynieuw, 0.350, 0.000, 3.141, -0.000]
walletpickup = p[walletpickupxnieuw, walletpickupynieuw, 0.20024, 0.000, 3.141, -0.000]

walletplacing1 = p[0.75741, 0.05235, 0.30632, 0.066, -3.063, -0.423]
prewalletpickupangled = p[0.55499, -0.42618, 0.34358, 0.0, 3.131, -0.216] 
walletpickupangled = p[0.55534, -0.44182, 0.23071, 0.0, 3.131, -0.216]
angledyoffset = 0.03554
angledzoffset = 4.92

walletpickupanglednr3y = -0.44182 + (2 * angledyoffset)
walletpickupanglednr3z = 0.23071 - (2 * angledzoffset)
prewalletpickupanglednr3y = -0.42618 + (2 * angledyoffset)
prewalletpickupanglednr3z = 0.34358 - (2 * angledzoffset)
preprewalletpickupangled = p[0.55499, prewalletpickupanglednr3y, 0.6, 0.0, 3.131, -0.216] 

prewalletpickupangled = p[0.55499, prewalletpickupanglednr3y, prewalletpickupanglednr3z, 0.0, 3.131, -0.216] 
walletpickupangled = p[0.55534, walletpickupanglednr3y, walletpickupanglednr3z, 0.0, 3.131, -0.216]
  
postwalletplacing = p[0.76502, -0.06980, 0.30349, 0.037, -3.064, -0.428]

pickbox = p[0.75033, -0.07908, 0.21563, 0.128, -2.759, -1.450]
afterpickbox = p[0.75433, -0.07908, 0.51563, 0.128, -2.759, -1.450]
postafterpickboxturn2 = p[0.75336, -0.19095, 0.32833, 0.821, 1.531, 0.899]
postafterpickboxturn1 = p[0.75333, -0.19095, 0.32830, 1.499, 1.801, 0.926]
postafterpickbox = p[0.75233, -0.07908, 0.51563, 2.469, -2.390, -2.263]
finalpospre1 = p[0.87482, 0.0, 0.64613, 2.469, -2.390, -2.263]
finalpospre2 = p[0.87482, 0.11870, 0.64613, 2.469, -2.390, -2.263]
finalposreal = p[0.87482, 0.15701, 0.64613, 2.469, -2.390, -2.263]

finalpospre1mid = p[0.78489, 0.0, 0.64613, 2.469, -2.390, -2.263]
finalpospre2mid = p[0.78489, 0.11870, 0.64613, 2.469, -2.390, -2.263]
finalposrealmid = p[0.78489, 0.15701, 0.64613, 2.469, -2.390, -2.263]


posb1 = p[0.25103, -0.69603, 0.3592, 0.039, 2.287, 2.151]
posb2 = p[0.25103, -0.69603, 0.09392, 0.039, 2.287, 2.151]
posb3 = p[0.25103, -0.69603, 0.06292, 0.039, 2.287, 2.151]
posb4 = p[0.25103, -0.7495, 0.06292, 0.039, 2.287, 2.151]
posb5 = p[0.25103, -0.7495, 0.04850, 0.039, 2.287, 2.151]
posb6 = p[0.25103, -0.69603, 0.04850, 0.039, 2.287, 2.151]


doosbovenmal = p[0.74101, -0.02802, 0.30504, 0.044, -2.812, -1.422]
doosbovenmal2 = p[0.73835, -0.05340, 0.28197, 0.025, -2.858, -1.271]
doosbovenmal3 = p[0.73584, -0.06893, 0.26790, 0.513, -2.904, -1.470]

doosinmal = p[0.74391, -0.04469, 0.24411, 0.25, -2.858, -1.271]


robotnamal = p[0.74101, -0.12100, 0.22794, 0.044, -2.812, -1.422]


####coords variabelene
failposGiftbox = p[0.29799, -0.32359, 0.32801, 2.397, -2.365, -2.423]
failposWallet = p[0.29799, -0.07908, 0.51563, 0.021, 3.131, -0.177]
home_pos = p[0.42109, -0.08926, 0.45336, 0, 3.141, 0]
afterpickbox = p[0.75433, -0.07908, 0.51563, 0.128, -2.759, -1.450]

###coords terugplaatsing giftbox
giftboxBack = p[0.80551, -0.06784, 0.65293, 2.383, 2.439, 2.345]
giftboxHalfInside = p[0.80551, 0.05933, 0.65293, 2.383, 2.439, 2.345]
giftboxCompleteInside = p[0.80551, 0.15412, 0.65293, 2.383, 2.439, 2.345]


####terugplaatsing giftbox in 


giftboxHalfInsideGripperClosedRow1 = p[0.88662, 0.03493, 0.65997, 2.469, -2.390, -2.263]
giftboxHalfInsideGripperClosedRow1 = p[0.88662, 0.03493, 0.65997, 2.469, -2.390, -2.263]
##gripper open
giftboxBackGripperClosedRow1 = p[0.88662, -0.00337, 0.65997, 2.469, -2.390, -2.263]
giftboxBackGripperClosedRow1ToTheLeft = p[0.87563, -0.00337, 0.65997, 2.469, -2.390, -2.263]
giftboxFullyInsideGripperClosedRow1 = p[0.87563, -0.14972, 0.65997, 2.469, -2.390, -2.263]



####vaste variabelen
prePickupYvoorGiftbox = 0.02985
afterPickupYvoorGiftbox = -0.06022
prePickupZvoorWallet = 0.350
afterPickupZvoorWallet = 0.350
walletSig = 1
giftboxSig = 0

########################################
# ----------- SOCKET -------------------
########################################

ip = "192.168.0.101"
socket_name = "socket1"
failCounterGiftbox = 0
failCounterWallet = 0

########################################
# ----------- HELPERS ------------------
########################################

def set_pose_z(pose, new_z):
    return p[pose[0], pose[1], new_z, pose[3], pose[4], pose[5]]
end

def set_pose_y(pose, new_y):
    return p[pose[0], new_y, pose[2], pose[3], pose[4], pose[5]]
end

def makepose(coords):
    return p[coords[2], coords[3], coords[4], coords[5], coords[6], coords[7]]
end

def get_sig(coords):
    return coords[1]
end

def get_fail(coords):
    return coords[8]
end

########################################
# ----------- IO -----------------------
########################################

def activate_suction_cup():
    set_standard_digital_out(0, True)
end

def deactivate_suction_cup():
    set_standard_digital_out(0, False)
end

def open_gripper():
    set_standard_analog_out(0, 0)
end

def close_gripper_pre_wallet():
    set_standard_analog_out(0, 0.275)
end

def close_gripper_full():
    set_standard_analog_out(0, 0.33)
end

########################################
# ----------- MOVES --------------------
########################################


def moveto_target_coords(coords):

    pose = makepose(coords)
    sig = get_sig(coords)
    set_standard_analog_out(0, 0)
    if sig == 1:
      set_standard_analog_out(0, 0.282)
    end

    
    if sig == 0:
       set_standard_analog_out(0, 0.0)
        movel(predoospickup, t = 0.1)
        set_standard_digital_out(0, True)
        movel(pose, t = 0.5)
   
        movel(predoospickup, t = 0.1)
        set_standard_analog_out(0, 0.33)
        sleep(0.7)
        set_standard_digital_out(0, False)
        #movel(postdoospickup)
    end
      
    if sig == 1:
        movej(prewalletpickup, t= 0.1)
        set_standard_analog_out(0, 0.275)
        sleep(2.5)
        set_standard_digital_out(1, True)
        sleep(0.5)
        set_standard_digital_out(2, True)
        set_standard_analog_out(1, 0.0)
   
   
   
   
        sleep(0.1)
        movel(pose, t = 0.1)
        set_standard_analog_out(0, 0.33)
        sleep(2)
        movel(prewalletpickup, t = 0.1)
    end
end 

def currentPlacingGiftboxBackCoords(currenIndex):
    

    ####halfinside -> halfplacedfurther 2.
    ##### backgripperclosedrow1 -> backpos 1.
    ###### backgripperclosedrow1totheleft -> backpos3  3.
    ###### fullyinside -> fullyinside 4.
    if currenIndex >= 1 and currenIndex <= 5:
        giftboxHalfInsideGripperClosedRow1 = p[0.89614, 0.05211, 0.65994, 2.469, -2.390, -2.263]
        ##gripper open
        giftboxBackGripperClosedRow1 = p[0.89614, -0.03299, 0.65994, 2.469, -2.390, -2.263]
        giftboxBackGripperClosedRow1ToTheLeft = p[0.87600, 0.01099, 0.67490, 2.469, -2.390, -2.263]
        giftboxFullyInsideGripperClosedRow1 = p[0.87600, 0.15080, 0.67490, 2.469, -2.390, -2.263]
    end
    if currenIndex >= 6 and currenIndex <= 10:
        giftboxHalfInsideGripperClosedRow1 = p[0.86294, 0.05211, 0.65994, 2.469, -2.390, -2.263]
        ##gripper open
        giftboxBackGripperClosedRow1 = p[0.86294, -0.03299, 0.65994, 2.469, -2.390, -2.263]
        giftboxBackGripperClosedRow1ToTheLeft = p[0.84600, 0.01099, 0.67490, 2.469, -2.390, -2.263]
        giftboxFullyInsideGripperClosedRow1 = p[0.84600, 0.15080, 0.67490, 2.469, -2.390, -2.263]
    end
    if currenIndex >= 11 and currenIndex <= 15:
        giftboxHalfInsideGripperClosedRow1 = p[0.82994, 0.05211, 0.65994, 2.469, -2.390, -2.263]
        ##gripper open
        giftboxBackGripperClosedRow1 = p[0.82994, -0.03299, 0.65994, 2.469, -2.390, -2.263]
        giftboxBackGripperClosedRow1ToTheLeft = p[0.81700, 0.01099, 0.67490, 2.469, -2.390, -2.263]
        giftboxFullyInsideGripperClosedRow1 = p[0.81700, 0.15080, 0.67490, 2.469, -2.390, -2.263]
    end
    if currenIndex >= 16 and currenIndex <= 20:
        giftboxHalfInsideGripperClosedRow1 = p[0.797994, 0.05211, 0.65994, 2.469, -2.390, -2.263]
        ##gripper open
        giftboxBackGripperClosedRow1 = p[0.79794, -0.03299, 0.65994, 2.469, -2.390, -2.263]
        giftboxBackGripperClosedRow1ToTheLeft = p[0.78500, 0.01099, 0.67490, 2.469, -2.390, -2.263]
        giftboxFullyInsideGripperClosedRow1 = p[0.78500, 0.15080, 0.67490, 2.469, -2.390, -2.263]
    end
    if currenIndex >= 21 and currenIndex <= 25:
         giftboxHalfInsideGripperClosedRow1 = p[0.76549, 0.05211, 0.65994, 2.469, -2.390, -2.263]
         ##gripper open
         giftboxBackGripperClosedRow1 = p[0.76549, -0.03299, 0.65994, 2.469, -2.390, -2.263]
         giftboxBackGripperClosedRow1ToTheLeft = p[0.74800, 0.01099, 0.67490, 2.469, -2.390, -2.263]
         giftboxFullyInsideGripperClosedRow1 = p[0.74800, 0.15080, 0.67490, 2.469, -2.390, -2.263]
    end
    if currenIndex >= 26 and currenIndex <= 30:
        giftboxHalfInsideGripperClosedRow1 = p[0.73394, 0.05211, 0.65994, 2.469, -2.390, -2.263]
        ##gripper open
        giftboxBackGripperClosedRow1 = p[0.73394, -0.03299, 0.65994, 2.469, -2.390, -2.263]
        giftboxBackGripperClosedRow1ToTheLeft = p[0.71600, 0.01099, 0.67490, 2.469, -2.390, -2.263]
        giftboxFullyInsideGripperClosedRow1 = p[0.71600, 0.15080, 0.67490, 2.469, -2.390, -2.263]
    end
   if currenIndex >= 31 and currenIndex <= 35:
        giftboxHalfInsideGripperClosedRow1 = p[0.70194, 0.05211, 0.65994, 2.469, -2.390, -2.263]
        ##gripper open
        giftboxBackGripperClosedRow1 = p[0.70194, -0.03299, 0.65994, 2.469, -2.390, -2.263]
        giftboxBackGripperClosedRow1ToTheLeft = p[0.68400, 0.01099, 0.67490, 2.469, -2.390, -2.263]
        giftboxFullyInsideGripperClosedRow1 = p[0.68400, 0.15080, 0.67490, 2.469, -2.390, -2.263]
    end
   if currenIndex >= 36 and currenIndex <= 40:
        giftboxHalfInsideGripperClosedRow1 = p[0.66994, 0.05211, 0.65994, 2.469, -2.390, -2.263]
        ##gripper open
        giftboxBackGripperClosedRow1 = p[0.66994, -0.03299, 0.65994, 2.469, -2.390, -2.263]
        giftboxBackGripperClosedRow1ToTheLeft = p[0.65200, 0.01099, 0.67490, 2.469, -2.390, -2.263]
        giftboxFullyInsideGripperClosedRow1 = p[0.65200, 0.15080, 0.67490, 2.469, -2.390, -2.263]
    end
    if currenIndex >= 41 and currenIndex <= 45:
        giftboxHalfInsideGripperClosedRow1 = p[0.63794, 0.05211, 0.65994, 2.469, -2.390, -2.263]
        ##gripper open
        giftboxBackGripperClosedRow1 = p[0.63794, -0.03299, 0.65994, 2.469, -2.390, -2.263]
        giftboxBackGripperClosedRow1ToTheLeft = p[0.60594, 0.01099, 0.67490, 2.469, -2.390, -2.263]
        giftboxFullyInsideGripperClosedRow1 = p[0.63794, 0.15080, 0.67490, 2.469, -2.390, -2.263]
    end
    if currenIndex >= 46 and currenIndex <= 50:
         giftboxHalfplacedFurther = p[0.60594, 0.05211, 0.65994, 2.469, -2.390, -2.263]
        ##gripper open
        giftboxbackpos = p[0.60594, -0.03299, 0.65994, 2.469, -2.390, -2.263]
        giftboxbackpos3 = p[0.60594, 0.01099, 0.67490, 2.469, -2.390, -2.263]

        giftboxRow10HalfInsideExtra = p[0.58151, 0.01090, 0.68080, 2.469, -2.390, -2.263]
        giftboxRow10BackPosExtra = p[0.58151, 0.07126, 0.68080, 2.469, -2.390, -2.263]
        giftboxRow10BackPosExtra2= p[0.58151, 0.06926, 0.68080, 2.469, -2.390, -2.263]
        giftboxRow10BackPosExtra3= p[0.58151, 0.06526, 0.68080, 2.469, -2.390, -2.263]

        giftboxFullyInsideGripperClosedRow1 = p[0.63794, 0.1528, 0.67490, 2.469, -2.390, -2.263]
giftboxFullyInside = p[0.63794, 0.1528, 0.67490, 2.469, -2.390, -2.263]        
giftbox10FullyInside = p[0.62136, 0.1523, 0.68080, 2.469, -2.390, -2.263]
        movel(giftboxbackpos, t = 0.1)
   	movel(giftboxHalfplacedFurther, t = 0.1)
   	set_standard_analog_out(0, 0.0)
   	sleep(1)
   	movel(giftboxbackpos3, t = 0.1)
   	set_standard_analog_out(0, 0.33)
   	sleep(1)
   	movel(giftboxRow10HalfInsideExtra, t = 0.1)
   	movel(giftboxRow10BackPosExtra2)
   	movel(giftboxRow10BackPosExtra3)
   	movel(giftbox10FullyInside, t = 0.1)
   	#movel(giftboxFullyInside, t = 0.1)
   	movel(giftboxbackpos3, t = 0.1)
	return False

    end
    movel(giftboxBackGripperClosedRow1, t = 0.1)
    movel(giftboxHalfInsideGripperClosedRow1, t = 0.1)
    set_standard_analog_out(0, 0.0)
    sleep(1)
    
    movel(giftboxBackGripperClosedRow1, t = 0.1)
    movel(giftboxBackGripperClosedRow1ToTheLeft, t = 0.1)
    set_standard_analog_out(0, 0.33)
    sleep(1)


    movel(giftboxFullyInsideGripperClosedRow1, t = 0.1)
    movel(giftboxBackGripperClosedRow1ToTheLeft, t = 0.1)
 


end


def failMove(sig):
    if sig == 0:    
        movel(failposGiftbox, t = 3)
        set_standard_analog_out(0, 0.0)
        failCounterGiftbox = failCounterGiftbox + 1
        failposGiftbox[1] = failposGiftbox[1] - 0.02
        failposGiftboxHoger = set_pose_z(failposGiftbox, afterPickupZvoorWallet)
        movel(failposGiftboxHoger, t=1)
        sleep(0.1)
    else:
        movel(failposWallet, t=3)
        textmsg(failposWallet)
        set_standard_analog_out(0, 0.0)
        failCounterWallet = failCounterWallet + 1
        failposWallet[1] = failposWallet[1] - 0.02
        failposWalletHoger = set_pose_z(failposWallet, afterPickupZvoorWallet)
        movel(failposWalletHoger, t=1)
        sleep(0.1)
    end
end

def pickupWallet(coords, fail, sig):
    pickupPose = makepose(coords)
    prePickupPose = set_pose_z(pickupPose, prePickupZvoorWallet)
    postpickup = set_pose_z(pickupPose, afterPickupZvoorWallet)
    #openBoxWithMold(prepickup)
    set_standard_analog_out(0, 0.29)
    set_standard_analog_out(1, 0.23)
    movej(prePickupPose, t= 0.1)
  
    movel(pickupPose, t = 0.1)
    set_standard_analog_out(0, 0.33)
    sleep(1)
    movel(prePickupPose, t = 0.1)
    
    sleep(1.2)
    set_standard_digital_out(1, True)
    sleep(0.1)
    set_standard_digital_out(2, True)
    set_standard_analog_out(1, 0.0)
    
    movej(posscan)
    
    
end

def pickupGiftbox(coords, fail, sig):
    set_standard_analog_out(0, 0.0)
    pickupPose = makepose(coords)
    prePickupPose = set_pose_y(pickupPose, prePickupYvoorGiftbox)
    postpickup = set_pose_y(pickupPose, afterPickupYvoorGiftbox)
    movel(prePickupPose, t = 0.1)
    set_standard_digital_out(0, True)
    movel(pickupPose, t = 0.5)
    movel(prePickupPose, t = 0.1)
    set_standard_analog_out(0, 0.33)
    sleep(0.7)
    set_standard_digital_out(0, False)
    movel(postpickup)
    sleep(0.1)
    if fail == 0:
        failMove(sig)

    else:
        movel(doosbovenmal, t = 0.5)
        movel(doosbovenmal2, t = 0.5)
        movel(doosinmal, t = 0.5)


        set_standard_analog_out(0, 0.24)
        movel(robotnamal, t = 1)
    end
    
end

def moveto_opener(sig, fail, coords):
    #fail = get_fail(coords)
    if sig == 1:
        pickupWallet(coords, fail, sig)
    else:
        pickupGiftbox(coords, fail, sig)
    end
end

def placingwalletAndDroppingGiftbox(currentIndex, correct):
    movej(postposscan, t = 0.4)
    movel(walletplacing1)
    set_standard_analog_out(0, 0.0)
    sleep(0.2)
    movel(postwalletplacing)
    set_standard_analog_out(1, 0.23) 
    sleep(1)
    set_standard_digital_out(2, False)
    sleep(0.1)
    set_standard_digital_out(1, False)
    set_standard_analog_out(1, 0.0) 
    set_standard_analog_out(0, 0.25)
    sleep(2)
    movel(pickbox, t = 0.1)
    set_standard_analog_out(0, 0.33)
    sleep(0.8)
    movel(afterpickbox, t = 0.1)
    #####hier logica voor foute wallet scan
    if correct == "true":
            movel(postafterpickbox, t = 0.1)
            currentPlacingGiftboxBackCoords(currentIndex)
    else:
             failWalletAndGiftbox()
    end	


    

end

def failWalletAndGiftbox():
    #movej(postposscan)
    #movel(walletplacing1)
    #set_standard_analog_out(0, 0.0)
    #sleep(0.2)
    #movel(postwalletplacing)
    #set_standard_analog_out(1, 0.23) 
    #sleep(1)
    #set_standard_digital_out(2, False)
    #sleep(0.1)
    #set_standard_digital_out(1, False)
    #set_standard_analog_out(1, 0.0) 
    #set_standard_analog_out(0, 0.25)
    #sleep(2)
    #movel(pickbox, t = 0.1)
    #set_standard_analog_out(0, 0.33)
    #sleep(0.)
    #movel(afterpickbox, t = 0.1)
    failMove(walletSig)
end
        


def pickupfinishedbox():
   set_standard_digital_out(2, False)
   set_standard_analog_out(0, 0.25)
   sleep(0.1)
   set_standard_digital_out(1, False)
   set_standard_analog_out(1, 0.0) 
   
   sleep(2)
   movel(pickbox, t = 0.1)
   
   set_standard_analog_out(0, 0.33)
   sleep(0.3)
   movel(afterpickbox, t = 0.1)
   movel(postafterpickbox, t = 0.5)
   movel(finalpospre1, t = 0.1)
   movel(finalpospre2, t = 0.1)
   set_standard_analog_out(0, 0.0)
   sleep(1)
   movel(finalposreal, t = 0.1)
   movel(finalpospre1, t = 0.1)
   movej(predoospickup, t = 0.1)

end 

def moveto_scanner():
    movej(posscan, a=1.2, v=0.25)
end

def moveto_home():
    movel(home_pos, a=1.2, v=0.25)
end

def is_homing_coord(coords, homing_list):
   tol = 0.0001
   i = 0
   check = True
   while i <=  7:
        textmsg(coords[i])
        textmsg(homing_list[i])
        value = coords[i] - homing_list[i]
        textmsg(value)
          if value < 0:
           value = -value
          end
       if value > tol:
          check = False
          break
       end
       i = i + 1
    end
    if check == False:
       return False
    else:
       return True
    end
   end

    


def main():
    homing_coords = [8, 0, 0, 0, 0, 0, 0, 0, 0]
    socket_open(ip, 12344, socket_name)
    testmsg = socket_read_string(socket_name, timeout=0)
    failposGiftbox = p[0.15934, -0.31519, 0.38262, 0.000, 3.141, 0.000]
    failposWallet = p[0.33442, -0.31519, 0.38262, 0.000, 3.141, 0.000]
#failposWallet = p[0.29799, -0.02612, 0.32801, 0.021, 3.131, -0.177]
    currentIndex = 1

    while True:
        textmsg(testmsg)
        testmsg = socket_read_string(socket_name, timeout=0)
        if testmsg == "start":
            break
        end
        sleep(0.1)
    end

    while True:

        ########send giftbox send, recv and move
        socket_send_string("SEND_GIFTBOX_COORDINATES", socket_name)
        coords = socket_read_ascii_float(8, socket_name, timeout=0)
        textmsg("Received coordinates:", coords)
        sig = get_sig(coords)
        fail = get_fail(coords)

        #textmsg("Received coordinates: ", coords)
        ####als de server zegt stop dan bewegen naar home en dan stoppen
        
        ###pickup giftbox als hij niet moest homen 
        moveto_opener(sig, fail,  coords)
        

        ####wallet coords send, recv and move
        socket_send_string("SEND_WALLET_COORDINATES", socket_name)
        coordsWallet = socket_read_ascii_float(8, socket_name, timeout=0)
        textmsg("Received coordinates: ",  coordsWallet)
        set_standard_analog_out(0, 0.275)
        sigWallet = get_sig(coordsWallet)
        failWallet = get_fail(coordsWallet)
        if failWallet == 1:
        	moveto_opener(sigWallet, failWallet, coordsWallet)
        end



        #####wallet scannen send, recv and move
        if failWallet ==1:
        	socket_send_string("SCAN_WALLET", socket_name)
        	correct = socket_read_string(socket_name, timeout=0)
        	textmsg("passed check: ",  correct)
	placingwalletAndDroppingGiftbox(currentIndex,correct)
        end

        #####cycle completed send, recv and move
        socket_send_string("CYCLE_COMPLETED", socket_name)
        correct = socket_read_string(socket_name, timeout=0)
        if correct == "false":
            textmsg("Homing robot")
            moveto_home()
            break
        end
        textmsg("Received coordinates: ", correct)
        currentIndex = currentIndex + 1

        sleep(0.01)
    end

    socket_close(socket_name)
end

########################################
# ----------- START --------------------
########################################

main()
