from state_enum import state_enum

class SMNState:
    IDLE = state_enum.IDLE
    SCANNING_GIFTBOX = state_enum.SCANNING_GIFTBOX
    SWITCH_CAMERA = state_enum.SWITCH_CAMERA
    SCANNING_WALLET = state_enum.SCANNING_WALLET
    PROCESSING = state_enum.PROCESSING
    ERROR = state_enum.ERROR
    SEND_WALLET_COORDINATES = state_enum.SEND_WALLET_COORDINATES
    SEND_GIFTBOX_DOORDINATES = state_enum.SEND_GIFTBOX_DOORDINATES
    DONE_CYCLE = state_enum.DONE_CYCLE

class Event:
    START_SCAN_GIFTBOX = "SCAN_GIFTBOX"
    SWITCH_CAMERA = "SWITCH_CAMERA"
    START_SCAN_WALLET = "SCAN_WALLET"
    PROCESS_DATA = "PROCESS_DATA"
    ERROR_OCCURRED = "ERROR"
    CYCLE_COMPLETED = "CYCLE_COMPLETED"
    IDLE = "IDLE"

CHANGE = {
    SMNState.IDLE: {
        Event.START_SCAN_GIFTBOX: SMNState.SCANNING_GIFTBOX
    },
    SMNState.SCANNING_GIFTBOX: {
        Event.SWITCH_CAMERA: SMNState.SWITCH_CAMERA,
        Event.ERROR_OCCURRED: SMNState.ERROR
    },
    SMNState.SWITCH_CAMERA: {
        Event.START_SCAN_WALLET: SMNState.SCANNING_WALLET,
        Event.ERROR_OCCURRED: SMNState.ERROR
    },
    SMNState.SCANNING_WALLET: {
        Event.PROCESS_DATA: SMNState.PROCESSING,
        Event.ERROR_OCCURRED: SMNState.ERROR
    },

    SMNState.PROCESSING: {
        Event.CYCLE_COMPLETED: SMNState.DONE_CYCLE,
        Event.ERROR_OCCURRED: SMNState.ERROR

    },
    SMNState.ERROR: {

        Event.CYCLE_COMPLETED: SMNState.DONE_CYCLE

    },
    SMNState.DONE_CYCLE: {
        Event.IDLE: SMNState.IDLE
    }
    }

CMD_TO_STATE = {
    "SCAN_GIFTBOX": SMNState.SCANNING_GIFTBOX,
    "SWITCH_CAMERA": SMNState.SWITCH_CAMERA,
    "SCAN_WALLET": SMNState.SCANNING_WALLET,
    "PROCESS_DATA": SMNState.PROCESSING,
    "ERROR": SMNState.ERROR,
    "CYCLE_COMPLETED": SMNState.DONE_CYCLE,
    "IDLE": SMNState.IDLE
}